name : api etl pipeline

on:
  push:
    branches:
      - main

jobs:

  fetch-api-data : 


    runs-on: ubuntu-latest

    steps:
      - name : checkout repo
        uses : actions/checkout@v2

      - name : setup python
        uses : actions/setup-python@v6
        with :
          python-version : '3.10'

      - name : install dependencies
        run : pip install -r requirements.txt

      - name : run api etl script
        run : python read_data_api.py

  fetch-data : 


    runs-on: ubuntu-latest

    steps:
      - name : checkout repo
        uses : actions/checkout@v2

      - name : setup python
        uses : actions/setup-python@v6
        with :
          python-version : '3.10'

      - name : install dependencies
        run : pip install -r requirements.txt

      - name : run data script
        env:
          API_TOKEN : ${{ secrets.API_TOKEN }}
        run : python api.py

        